module.exports = [
  {
    "title": "Two Sum",
    "slug": "two-sum-lc1",
    "canonicalKey": "lc1",
    "link": "https://leetcode.com/problems/two-sum/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 1
  },
  {
    "title": "Best Time to Buy and Sell Stock",
    "slug": "best-time-to-buy-and-sell-stock-lc121",
    "canonicalKey": "lc121",
    "link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 2
  },
  {
    "title": "Contains Duplicate",
    "slug": "contains-duplicate-lc217",
    "canonicalKey": "lc217",
    "link": "https://leetcode.com/problems/contains-duplicate/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 3
  },
  {
    "title": "Product of Array Except Self",
    "slug": "product-of-array-except-self-lc238",
    "canonicalKey": "lc238",
    "link": "https://leetcode.com/problems/product-of-array-except-self/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 4
  },
  {
    "title": "Maximum Subarray",
    "slug": "maximum-subarray-lc53",
    "canonicalKey": "lc53",
    "link": "https://leetcode.com/problems/maximum-subarray/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 5
  },
  {
    "title": "Maximum Product Subarray",
    "slug": "maximum-product-subarray-lc152",
    "canonicalKey": "lc152",
    "link": "https://leetcode.com/problems/maximum-product-subarray/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 6
  },
  {
    "title": "Find Minimum in Rotated Sorted Array",
    "slug": "find-minimum-in-rotated-sorted-array-lc153",
    "canonicalKey": "lc153",
    "link": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 7
  },
  {
    "title": "Search in Rotated Sorted Array",
    "slug": "search-in-rotated-sorted-array-lc33",
    "canonicalKey": "lc33",
    "link": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 8
  },
  {
    "title": "3Sum",
    "slug": "3sum-lc15",
    "canonicalKey": "lc15",
    "link": "https://leetcode.com/problems/3sum/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "blind75",
    "order": 9
  },
  {
    "title": "Longest Substring Without Repeating Characters",
    "slug": "longest-substring-without-repeating-characters-lc3",
    "canonicalKey": "lc3",
    "link": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "blind75",
    "order": 10
  },
  {
    "title": "Longest Repeating Character Replacement",
    "slug": "longest-repeating-character-replacement-lc424",
    "canonicalKey": "lc424",
    "link": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "blind75",
    "order": 11
  },
  {
    "title": "Minimum Window Substring",
    "slug": "minimum-window-substring-lc76",
    "canonicalKey": "lc76",
    "link": "https://leetcode.com/problems/minimum-window-substring/",
    "difficulty": "Hard",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "blind75",
    "order": 12
  },
  {
    "title": "Valid Anagram",
    "slug": "valid-anagram-lc242",
    "canonicalKey": "lc242",
    "link": "https://leetcode.com/problems/valid-anagram/",
    "difficulty": "Easy",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "blind75",
    "order": 13
  },
  {
    "title": "Group Anagrams",
    "slug": "group-anagrams-lc49",
    "canonicalKey": "lc49",
    "link": "https://leetcode.com/problems/group-anagrams/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "blind75",
    "order": 14
  },
  {
    "title": "Valid Palindrome",
    "slug": "valid-palindrome-lc125",
    "canonicalKey": "lc125",
    "link": "https://leetcode.com/problems/valid-palindrome/",
    "difficulty": "Easy",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "blind75",
    "order": 15
  },
  {
    "title": "Container With Most Water",
    "slug": "container-with-most-water-lc11",
    "canonicalKey": "lc11",
    "link": "https://leetcode.com/problems/container-with-most-water/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "blind75",
    "order": 16
  },
  {
    "title": "Binary Search",
    "slug": "binary-search-lc704",
    "canonicalKey": "lc704",
    "link": "https://leetcode.com/problems/binary-search/",
    "difficulty": "Easy",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "blind75",
    "order": 17
  },
  {
    "title": "Search a 2D Matrix",
    "slug": "search-a-2d-matrix-lc74",
    "canonicalKey": "lc74",
    "link": "https://leetcode.com/problems/search-a-2d-matrix/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "blind75",
    "order": 18
  },
  {
    "title": "Reverse Linked List",
    "slug": "reverse-linked-list-lc206",
    "canonicalKey": "lc206",
    "link": "https://leetcode.com/problems/reverse-linked-list/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 19
  },
  {
    "title": "Linked List Cycle",
    "slug": "linked-list-cycle-lc141",
    "canonicalKey": "lc141",
    "link": "https://leetcode.com/problems/linked-list-cycle/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 20
  },
  {
    "title": "Merge Two Sorted Lists",
    "slug": "merge-two-sorted-lists-lc21",
    "canonicalKey": "lc21",
    "link": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 21
  },
  {
    "title": "Merge K Sorted Lists",
    "slug": "merge-k-sorted-lists-lc23",
    "canonicalKey": "lc23",
    "link": "https://leetcode.com/problems/merge-k-sorted-lists/",
    "difficulty": "Hard",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 22
  },
  {
    "title": "Remove Nth Node From End of List",
    "slug": "remove-nth-node-from-end-of-list-lc19",
    "canonicalKey": "lc19",
    "link": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 23
  },
  {
    "title": "Reorder List",
    "slug": "reorder-list-lc143",
    "canonicalKey": "lc143",
    "link": "https://leetcode.com/problems/reorder-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "blind75",
    "order": 24
  },
  {
    "title": "Maximum Depth of Binary Tree",
    "slug": "maximum-depth-of-binary-tree-lc104",
    "canonicalKey": "lc104",
    "link": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 25
  },
  {
    "title": "Same Tree",
    "slug": "same-tree-lc100",
    "canonicalKey": "lc100",
    "link": "https://leetcode.com/problems/same-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 26
  },
  {
    "title": "Invert Binary Tree",
    "slug": "invert-binary-tree-lc226",
    "canonicalKey": "lc226",
    "link": "https://leetcode.com/problems/invert-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 27
  },
  {
    "title": "Binary Tree Maximum Path Sum",
    "slug": "binary-tree-maximum-path-sum-lc124",
    "canonicalKey": "lc124",
    "link": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 28
  },
  {
    "title": "Binary Tree Level Order Traversal",
    "slug": "binary-tree-level-order-traversal-lc102",
    "canonicalKey": "lc102",
    "link": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 29
  },
  {
    "title": "Serialize and Deserialize Binary Tree",
    "slug": "serialize-and-deserialize-binary-tree-lc297",
    "canonicalKey": "lc297",
    "link": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 30
  },
  {
    "title": "Subtree of Another Tree",
    "slug": "subtree-of-another-tree-lc572",
    "canonicalKey": "lc572",
    "link": "https://leetcode.com/problems/subtree-of-another-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 31
  },
  {
    "title": "Construct Binary Tree from Preorder and Inorder",
    "slug": "construct-binary-tree-from-preorder-and-inorder-lc105",
    "canonicalKey": "lc105",
    "link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 32
  },
  {
    "title": "Validate Binary Search Tree",
    "slug": "validate-binary-search-tree-lc98",
    "canonicalKey": "lc98",
    "link": "https://leetcode.com/problems/validate-binary-search-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 33
  },
  {
    "title": "Kth Smallest Element in a BST",
    "slug": "kth-smallest-element-in-a-bst-lc230",
    "canonicalKey": "lc230",
    "link": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 34
  },
  {
    "title": "Lowest Common Ancestor of a BST",
    "slug": "lowest-common-ancestor-of-a-bst-lc235",
    "canonicalKey": "lc235",
    "link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "blind75",
    "order": 35
  },
  {
    "title": "Number of Islands",
    "slug": "number-of-islands-lc200",
    "canonicalKey": "lc200",
    "link": "https://leetcode.com/problems/number-of-islands/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 36
  },
  {
    "title": "Clone Graph",
    "slug": "clone-graph-lc133",
    "canonicalKey": "lc133",
    "link": "https://leetcode.com/problems/clone-graph/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 37
  },
  {
    "title": "Pacific Atlantic Water Flow",
    "slug": "pacific-atlantic-water-flow-lc417",
    "canonicalKey": "lc417",
    "link": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 38
  },
  {
    "title": "Course Schedule",
    "slug": "course-schedule-lc207",
    "canonicalKey": "lc207",
    "link": "https://leetcode.com/problems/course-schedule/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 39
  },
  {
    "title": "Graph Valid Tree",
    "slug": "graph-valid-tree-lc261",
    "canonicalKey": "lc261",
    "link": "https://leetcode.com/problems/graph-valid-tree/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 40
  },
  {
    "title": "Number of Connected Components",
    "slug": "number-of-connected-components-lc323",
    "canonicalKey": "lc323",
    "link": "https://leetcode.com/problems/number-of-connected-components/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "blind75",
    "order": 41
  },
  {
    "title": "Climbing Stairs",
    "slug": "climbing-stairs-lc70",
    "canonicalKey": "lc70",
    "link": "https://leetcode.com/problems/climbing-stairs/",
    "difficulty": "Easy",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 42
  },
  {
    "title": "House Robber",
    "slug": "house-robber-lc198",
    "canonicalKey": "lc198",
    "link": "https://leetcode.com/problems/house-robber/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 43
  },
  {
    "title": "House Robber II",
    "slug": "house-robber-ii-lc213",
    "canonicalKey": "lc213",
    "link": "https://leetcode.com/problems/house-robber-ii/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 44
  },
  {
    "title": "Coin Change",
    "slug": "coin-change-lc322",
    "canonicalKey": "lc322",
    "link": "https://leetcode.com/problems/coin-change/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 45
  },
  {
    "title": "Longest Increasing Subsequence",
    "slug": "longest-increasing-subsequence-lc300",
    "canonicalKey": "lc300",
    "link": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 46
  },
  {
    "title": "Word Break",
    "slug": "word-break-lc139",
    "canonicalKey": "lc139",
    "link": "https://leetcode.com/problems/word-break/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 47
  },
  {
    "title": "Combination Sum IV",
    "slug": "combination-sum-iv-lc377",
    "canonicalKey": "lc377",
    "link": "https://leetcode.com/problems/combination-sum-iv/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 48
  },
  {
    "title": "Unique Paths",
    "slug": "unique-paths-lc62",
    "canonicalKey": "lc62",
    "link": "https://leetcode.com/problems/unique-paths/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 49
  },
  {
    "title": "Longest Common Subsequence",
    "slug": "longest-common-subsequence-lc1143",
    "canonicalKey": "lc1143",
    "link": "https://leetcode.com/problems/longest-common-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 50
  },
  {
    "title": "Decode Ways",
    "slug": "decode-ways-lc91",
    "canonicalKey": "lc91",
    "link": "https://leetcode.com/problems/decode-ways/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "blind75",
    "order": 51
  },
  {
    "title": "Maximum Subarray",
    "slug": "maximum-subarray-lc53-2",
    "canonicalKey": "lc53",
    "link": "https://leetcode.com/problems/maximum-subarray/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 52
  },
  {
    "title": "Jump Game",
    "slug": "jump-game-lc55",
    "canonicalKey": "lc55",
    "link": "https://leetcode.com/problems/jump-game/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 53
  },
  {
    "title": "Jump Game II",
    "slug": "jump-game-ii-lc45",
    "canonicalKey": "lc45",
    "link": "https://leetcode.com/problems/jump-game-ii/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 54
  },
  {
    "title": "Gas Station",
    "slug": "gas-station-lc134",
    "canonicalKey": "lc134",
    "link": "https://leetcode.com/problems/gas-station/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 55
  },
  {
    "title": "Partition Labels",
    "slug": "partition-labels-lc763",
    "canonicalKey": "lc763",
    "link": "https://leetcode.com/problems/partition-labels/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 56
  },
  {
    "title": "Merge Triplets to Form Target Triplet",
    "slug": "merge-triplets-to-form-target-triplet-lc1899",
    "canonicalKey": "lc1899",
    "link": "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "blind75",
    "order": 57
  },
  {
    "title": "Merge Intervals",
    "slug": "merge-intervals-lc56",
    "canonicalKey": "lc56",
    "link": "https://leetcode.com/problems/merge-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 58
  },
  {
    "title": "Insert Interval",
    "slug": "insert-interval-lc57",
    "canonicalKey": "lc57",
    "link": "https://leetcode.com/problems/insert-interval/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 59
  },
  {
    "title": "Non-overlapping Intervals",
    "slug": "non-overlapping-intervals-lc435",
    "canonicalKey": "lc435",
    "link": "https://leetcode.com/problems/non-overlapping-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 60
  },
  {
    "title": "Meeting Rooms",
    "slug": "meeting-rooms-lc252",
    "canonicalKey": "lc252",
    "link": "https://leetcode.com/problems/meeting-rooms/",
    "difficulty": "Easy",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 61
  },
  {
    "title": "Meeting Rooms II",
    "slug": "meeting-rooms-ii-lc253",
    "canonicalKey": "lc253",
    "link": "https://leetcode.com/problems/meeting-rooms-ii/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 62
  },
  {
    "title": "Minimum Window Substring",
    "slug": "minimum-window-substring-lc76-2",
    "canonicalKey": "lc76",
    "link": "https://leetcode.com/problems/minimum-window-substring/",
    "difficulty": "Hard",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "blind75",
    "order": 63
  },
  {
    "title": "Find Median from Data Stream",
    "slug": "find-median-from-data-stream-lc295",
    "canonicalKey": "lc295",
    "link": "https://leetcode.com/problems/find-median-from-data-stream/",
    "difficulty": "Hard",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "blind75",
    "order": 64
  },
  {
    "title": "Top K Frequent Elements",
    "slug": "top-k-frequent-elements-lc347",
    "canonicalKey": "lc347",
    "link": "https://leetcode.com/problems/top-k-frequent-elements/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "blind75",
    "order": 65
  },
  {
    "title": "Combination Sum",
    "slug": "combination-sum-lc39",
    "canonicalKey": "lc39",
    "link": "https://leetcode.com/problems/combination-sum/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "blind75",
    "order": 66
  },
  {
    "title": "Word Search",
    "slug": "word-search-lc79",
    "canonicalKey": "lc79",
    "link": "https://leetcode.com/problems/word-search/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "blind75",
    "order": 67
  },
  {
    "title": "Subsets",
    "slug": "subsets-lc78",
    "canonicalKey": "lc78",
    "link": "https://leetcode.com/problems/subsets/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "blind75",
    "order": 68
  },
  {
    "title": "Single Number",
    "slug": "single-number-lc136",
    "canonicalKey": "lc136",
    "link": "https://leetcode.com/problems/single-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "blind75",
    "order": 69
  },
  {
    "title": "Number of 1 Bits",
    "slug": "number-of-1-bits-lc191",
    "canonicalKey": "lc191",
    "link": "https://leetcode.com/problems/number-of-1-bits/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "blind75",
    "order": 70
  },
  {
    "title": "Counting Bits",
    "slug": "counting-bits-lc338",
    "canonicalKey": "lc338",
    "link": "https://leetcode.com/problems/counting-bits/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "blind75",
    "order": 71
  },
  {
    "title": "Missing Number",
    "slug": "missing-number-lc268",
    "canonicalKey": "lc268",
    "link": "https://leetcode.com/problems/missing-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "blind75",
    "order": 72
  },
  {
    "title": "Reverse Bits",
    "slug": "reverse-bits-lc190",
    "canonicalKey": "lc190",
    "link": "https://leetcode.com/problems/reverse-bits/",
    "difficulty": "Easy",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "blind75",
    "order": 73
  },
  {
    "title": "Rotate Image",
    "slug": "rotate-image-lc48",
    "canonicalKey": "lc48",
    "link": "https://leetcode.com/problems/rotate-image/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "blind75",
    "order": 74
  },
  {
    "title": "Set Matrix Zeroes",
    "slug": "set-matrix-zeroes-lc73",
    "canonicalKey": "lc73",
    "link": "https://leetcode.com/problems/set-matrix-zeroes/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "blind75",
    "order": 75
  }
];
