module.exports = [
  {
    "title": "Contains Duplicate",
    "slug": "contains-duplicate-lc217",
    "canonicalKey": "lc217",
    "link": "https://leetcode.com/problems/contains-duplicate/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 1
  },
  {
    "title": "Valid Anagram",
    "slug": "valid-anagram-lc242",
    "canonicalKey": "lc242",
    "link": "https://leetcode.com/problems/valid-anagram/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 2
  },
  {
    "title": "Two Sum",
    "slug": "two-sum-lc1",
    "canonicalKey": "lc1",
    "link": "https://leetcode.com/problems/two-sum/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 3
  },
  {
    "title": "Group Anagrams",
    "slug": "group-anagrams-lc49",
    "canonicalKey": "lc49",
    "link": "https://leetcode.com/problems/group-anagrams/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 4
  },
  {
    "title": "Top K Frequent Elements",
    "slug": "top-k-frequent-elements-lc347",
    "canonicalKey": "lc347",
    "link": "https://leetcode.com/problems/top-k-frequent-elements/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 5
  },
  {
    "title": "Product of Array Except Self",
    "slug": "product-of-array-except-self-lc238",
    "canonicalKey": "lc238",
    "link": "https://leetcode.com/problems/product-of-array-except-self/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 6
  },
  {
    "title": "Valid Sudoku",
    "slug": "valid-sudoku-lc36",
    "canonicalKey": "lc36",
    "link": "https://leetcode.com/problems/valid-sudoku/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 7
  },
  {
    "title": "Encode and Decode Strings",
    "slug": "encode-and-decode-strings-lc271",
    "canonicalKey": "lc271",
    "link": "https://leetcode.com/problems/encode-and-decode-strings/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 8
  },
  {
    "title": "Longest Consecutive Sequence",
    "slug": "longest-consecutive-sequence-lc128",
    "canonicalKey": "lc128",
    "link": "https://leetcode.com/problems/longest-consecutive-sequence/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "neetcode150",
    "order": 9
  },
  {
    "title": "Valid Palindrome",
    "slug": "valid-palindrome-lc125",
    "canonicalKey": "lc125",
    "link": "https://leetcode.com/problems/valid-palindrome/",
    "difficulty": "Easy",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "neetcode150",
    "order": 10
  },
  {
    "title": "Two Sum II - Input Array Is Sorted",
    "slug": "two-sum-ii-input-array-is-sorted-lc167",
    "canonicalKey": "lc167",
    "link": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "neetcode150",
    "order": 11
  },
  {
    "title": "3Sum",
    "slug": "3sum-lc15",
    "canonicalKey": "lc15",
    "link": "https://leetcode.com/problems/3sum/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "neetcode150",
    "order": 12
  },
  {
    "title": "Container With Most Water",
    "slug": "container-with-most-water-lc11",
    "canonicalKey": "lc11",
    "link": "https://leetcode.com/problems/container-with-most-water/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "neetcode150",
    "order": 13
  },
  {
    "title": "Trapping Rain Water",
    "slug": "trapping-rain-water-lc42",
    "canonicalKey": "lc42",
    "link": "https://leetcode.com/problems/trapping-rain-water/",
    "difficulty": "Hard",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "neetcode150",
    "order": 14
  },
  {
    "title": "Best Time to Buy and Sell Stock",
    "slug": "best-time-to-buy-and-sell-stock-lc121",
    "canonicalKey": "lc121",
    "link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "difficulty": "Easy",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 15
  },
  {
    "title": "Longest Substring Without Repeating Characters",
    "slug": "longest-substring-without-repeating-characters-lc3",
    "canonicalKey": "lc3",
    "link": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "difficulty": "Medium",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 16
  },
  {
    "title": "Longest Repeating Character Replacement",
    "slug": "longest-repeating-character-replacement-lc424",
    "canonicalKey": "lc424",
    "link": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "difficulty": "Medium",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 17
  },
  {
    "title": "Permutation in String",
    "slug": "permutation-in-string-lc567",
    "canonicalKey": "lc567",
    "link": "https://leetcode.com/problems/permutation-in-string/",
    "difficulty": "Medium",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 18
  },
  {
    "title": "Minimum Window Substring",
    "slug": "minimum-window-substring-lc76",
    "canonicalKey": "lc76",
    "link": "https://leetcode.com/problems/minimum-window-substring/",
    "difficulty": "Hard",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 19
  },
  {
    "title": "Sliding Window Maximum",
    "slug": "sliding-window-maximum-lc239",
    "canonicalKey": "lc239",
    "link": "https://leetcode.com/problems/sliding-window-maximum/",
    "difficulty": "Hard",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "neetcode150",
    "order": 20
  },
  {
    "title": "Valid Parentheses",
    "slug": "valid-parentheses-lc20",
    "canonicalKey": "lc20",
    "link": "https://leetcode.com/problems/valid-parentheses/",
    "difficulty": "Easy",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 21
  },
  {
    "title": "Min Stack",
    "slug": "min-stack-lc155",
    "canonicalKey": "lc155",
    "link": "https://leetcode.com/problems/min-stack/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 22
  },
  {
    "title": "Evaluate Reverse Polish Notation",
    "slug": "evaluate-reverse-polish-notation-lc150",
    "canonicalKey": "lc150",
    "link": "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 23
  },
  {
    "title": "Generate Parentheses",
    "slug": "generate-parentheses-lc22",
    "canonicalKey": "lc22",
    "link": "https://leetcode.com/problems/generate-parentheses/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 24
  },
  {
    "title": "Daily Temperatures",
    "slug": "daily-temperatures-lc739",
    "canonicalKey": "lc739",
    "link": "https://leetcode.com/problems/daily-temperatures/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 25
  },
  {
    "title": "Car Fleet",
    "slug": "car-fleet-lc853",
    "canonicalKey": "lc853",
    "link": "https://leetcode.com/problems/car-fleet/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 26
  },
  {
    "title": "Largest Rectangle in Histogram",
    "slug": "largest-rectangle-in-histogram-lc84",
    "canonicalKey": "lc84",
    "link": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "difficulty": "Hard",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "neetcode150",
    "order": 27
  },
  {
    "title": "Binary Search",
    "slug": "binary-search-lc704",
    "canonicalKey": "lc704",
    "link": "https://leetcode.com/problems/binary-search/",
    "difficulty": "Easy",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 28
  },
  {
    "title": "Search a 2D Matrix",
    "slug": "search-a-2d-matrix-lc74",
    "canonicalKey": "lc74",
    "link": "https://leetcode.com/problems/search-a-2d-matrix/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 29
  },
  {
    "title": "Koko Eating Bananas",
    "slug": "koko-eating-bananas-lc875",
    "canonicalKey": "lc875",
    "link": "https://leetcode.com/problems/koko-eating-bananas/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 30
  },
  {
    "title": "Find Minimum in Rotated Sorted Array",
    "slug": "find-minimum-in-rotated-sorted-array-lc153",
    "canonicalKey": "lc153",
    "link": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 31
  },
  {
    "title": "Search in Rotated Sorted Array",
    "slug": "search-in-rotated-sorted-array-lc33",
    "canonicalKey": "lc33",
    "link": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 32
  },
  {
    "title": "Time Based Key-Value Store",
    "slug": "time-based-key-value-store-lc981",
    "canonicalKey": "lc981",
    "link": "https://leetcode.com/problems/time-based-key-value-store/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 33
  },
  {
    "title": "Median of Two Sorted Arrays",
    "slug": "median-of-two-sorted-arrays-lc4",
    "canonicalKey": "lc4",
    "link": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "difficulty": "Hard",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "neetcode150",
    "order": 34
  },
  {
    "title": "Reverse Linked List",
    "slug": "reverse-linked-list-lc206",
    "canonicalKey": "lc206",
    "link": "https://leetcode.com/problems/reverse-linked-list/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 35
  },
  {
    "title": "Merge Two Sorted Lists",
    "slug": "merge-two-sorted-lists-lc21",
    "canonicalKey": "lc21",
    "link": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 36
  },
  {
    "title": "Reorder List",
    "slug": "reorder-list-lc143",
    "canonicalKey": "lc143",
    "link": "https://leetcode.com/problems/reorder-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 37
  },
  {
    "title": "Remove Nth Node From End of List",
    "slug": "remove-nth-node-from-end-of-list-lc19",
    "canonicalKey": "lc19",
    "link": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 38
  },
  {
    "title": "Copy List With Random Pointer",
    "slug": "copy-list-with-random-pointer-lc138",
    "canonicalKey": "lc138",
    "link": "https://leetcode.com/problems/copy-list-with-random-pointer/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 39
  },
  {
    "title": "Add Two Numbers",
    "slug": "add-two-numbers-lc2",
    "canonicalKey": "lc2",
    "link": "https://leetcode.com/problems/add-two-numbers/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 40
  },
  {
    "title": "Linked List Cycle",
    "slug": "linked-list-cycle-lc141",
    "canonicalKey": "lc141",
    "link": "https://leetcode.com/problems/linked-list-cycle/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 41
  },
  {
    "title": "Find the Duplicate Number",
    "slug": "find-the-duplicate-number-lc287",
    "canonicalKey": "lc287",
    "link": "https://leetcode.com/problems/find-the-duplicate-number/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 42
  },
  {
    "title": "LRU Cache",
    "slug": "lru-cache-lc146",
    "canonicalKey": "lc146",
    "link": "https://leetcode.com/problems/lru-cache/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 43
  },
  {
    "title": "Merge K Sorted Lists",
    "slug": "merge-k-sorted-lists-lc23",
    "canonicalKey": "lc23",
    "link": "https://leetcode.com/problems/merge-k-sorted-lists/",
    "difficulty": "Hard",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 44
  },
  {
    "title": "Reverse Nodes in K-Group",
    "slug": "reverse-nodes-in-k-group-lc25",
    "canonicalKey": "lc25",
    "link": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "difficulty": "Hard",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "neetcode150",
    "order": 45
  },
  {
    "title": "Invert Binary Tree",
    "slug": "invert-binary-tree-lc226",
    "canonicalKey": "lc226",
    "link": "https://leetcode.com/problems/invert-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 46
  },
  {
    "title": "Maximum Depth of Binary Tree",
    "slug": "maximum-depth-of-binary-tree-lc104",
    "canonicalKey": "lc104",
    "link": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 47
  },
  {
    "title": "Diameter of Binary Tree",
    "slug": "diameter-of-binary-tree-lc543",
    "canonicalKey": "lc543",
    "link": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 48
  },
  {
    "title": "Balanced Binary Tree",
    "slug": "balanced-binary-tree-lc110",
    "canonicalKey": "lc110",
    "link": "https://leetcode.com/problems/balanced-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 49
  },
  {
    "title": "Same Tree",
    "slug": "same-tree-lc100",
    "canonicalKey": "lc100",
    "link": "https://leetcode.com/problems/same-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 50
  },
  {
    "title": "Subtree of Another Tree",
    "slug": "subtree-of-another-tree-lc572",
    "canonicalKey": "lc572",
    "link": "https://leetcode.com/problems/subtree-of-another-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 51
  },
  {
    "title": "Lowest Common Ancestor of a BST",
    "slug": "lowest-common-ancestor-of-a-bst-lc235",
    "canonicalKey": "lc235",
    "link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 52
  },
  {
    "title": "Binary Tree Level Order Traversal",
    "slug": "binary-tree-level-order-traversal-lc102",
    "canonicalKey": "lc102",
    "link": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 53
  },
  {
    "title": "Binary Tree Right Side View",
    "slug": "binary-tree-right-side-view-lc199",
    "canonicalKey": "lc199",
    "link": "https://leetcode.com/problems/binary-tree-right-side-view/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 54
  },
  {
    "title": "Count Good Nodes in Binary Tree",
    "slug": "count-good-nodes-in-binary-tree-lc1448",
    "canonicalKey": "lc1448",
    "link": "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 55
  },
  {
    "title": "Validate Binary Search Tree",
    "slug": "validate-binary-search-tree-lc98",
    "canonicalKey": "lc98",
    "link": "https://leetcode.com/problems/validate-binary-search-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 56
  },
  {
    "title": "Kth Smallest Element in a BST",
    "slug": "kth-smallest-element-in-a-bst-lc230",
    "canonicalKey": "lc230",
    "link": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 57
  },
  {
    "title": "Construct Binary Tree from Preorder and Inorder",
    "slug": "construct-binary-tree-from-preorder-and-inorder-lc105",
    "canonicalKey": "lc105",
    "link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 58
  },
  {
    "title": "Binary Tree Maximum Path Sum",
    "slug": "binary-tree-maximum-path-sum-lc124",
    "canonicalKey": "lc124",
    "link": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 59
  },
  {
    "title": "Serialize and Deserialize Binary Tree",
    "slug": "serialize-and-deserialize-binary-tree-lc297",
    "canonicalKey": "lc297",
    "link": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "neetcode150",
    "order": 60
  },
  {
    "title": "Implement Trie",
    "slug": "implement-trie-lc208",
    "canonicalKey": "lc208",
    "link": "https://leetcode.com/problems/implement-trie/",
    "difficulty": "Medium",
    "category": "Tries",
    "pattern": "Tries",
    "sheet": "neetcode150",
    "order": 61
  },
  {
    "title": "Design Add and Search Words Data Structure",
    "slug": "design-add-and-search-words-data-structure-lc211",
    "canonicalKey": "lc211",
    "link": "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    "difficulty": "Medium",
    "category": "Tries",
    "pattern": "Tries",
    "sheet": "neetcode150",
    "order": 62
  },
  {
    "title": "Word Search II",
    "slug": "word-search-ii-lc212",
    "canonicalKey": "lc212",
    "link": "https://leetcode.com/problems/word-search-ii/",
    "difficulty": "Hard",
    "category": "Tries",
    "pattern": "Tries",
    "sheet": "neetcode150",
    "order": 63
  },
  {
    "title": "Kth Largest Element in a Stream",
    "slug": "kth-largest-element-in-a-stream-lc703",
    "canonicalKey": "lc703",
    "link": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    "difficulty": "Easy",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 64
  },
  {
    "title": "Last Stone Weight",
    "slug": "last-stone-weight-lc1046",
    "canonicalKey": "lc1046",
    "link": "https://leetcode.com/problems/last-stone-weight/",
    "difficulty": "Easy",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 65
  },
  {
    "title": "K Closest Points to Origin",
    "slug": "k-closest-points-to-origin-lc973",
    "canonicalKey": "lc973",
    "link": "https://leetcode.com/problems/k-closest-points-to-origin/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 66
  },
  {
    "title": "Kth Largest Element in an Array",
    "slug": "kth-largest-element-in-an-array-lc215",
    "canonicalKey": "lc215",
    "link": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 67
  },
  {
    "title": "Task Scheduler",
    "slug": "task-scheduler-lc621",
    "canonicalKey": "lc621",
    "link": "https://leetcode.com/problems/task-scheduler/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 68
  },
  {
    "title": "Design Twitter",
    "slug": "design-twitter-lc355",
    "canonicalKey": "lc355",
    "link": "https://leetcode.com/problems/design-twitter/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 69
  },
  {
    "title": "Find Median From Data Stream",
    "slug": "find-median-from-data-stream-lc295",
    "canonicalKey": "lc295",
    "link": "https://leetcode.com/problems/find-median-from-data-stream/",
    "difficulty": "Hard",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "neetcode150",
    "order": 70
  },
  {
    "title": "Subsets",
    "slug": "subsets-lc78",
    "canonicalKey": "lc78",
    "link": "https://leetcode.com/problems/subsets/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 71
  },
  {
    "title": "Combination Sum",
    "slug": "combination-sum-lc39",
    "canonicalKey": "lc39",
    "link": "https://leetcode.com/problems/combination-sum/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 72
  },
  {
    "title": "Permutations",
    "slug": "permutations-lc46",
    "canonicalKey": "lc46",
    "link": "https://leetcode.com/problems/permutations/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 73
  },
  {
    "title": "Subsets II",
    "slug": "subsets-ii-lc90",
    "canonicalKey": "lc90",
    "link": "https://leetcode.com/problems/subsets-ii/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 74
  },
  {
    "title": "Combination Sum II",
    "slug": "combination-sum-ii-lc40",
    "canonicalKey": "lc40",
    "link": "https://leetcode.com/problems/combination-sum-ii/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 75
  },
  {
    "title": "Word Search",
    "slug": "word-search-lc79",
    "canonicalKey": "lc79",
    "link": "https://leetcode.com/problems/word-search/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 76
  },
  {
    "title": "Palindrome Partitioning",
    "slug": "palindrome-partitioning-lc131",
    "canonicalKey": "lc131",
    "link": "https://leetcode.com/problems/palindrome-partitioning/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 77
  },
  {
    "title": "Letter Combinations of a Phone Number",
    "slug": "letter-combinations-of-a-phone-number-lc17",
    "canonicalKey": "lc17",
    "link": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 78
  },
  {
    "title": "N-Queens",
    "slug": "n-queens-lc51",
    "canonicalKey": "lc51",
    "link": "https://leetcode.com/problems/n-queens/",
    "difficulty": "Hard",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "neetcode150",
    "order": 79
  },
  {
    "title": "Number of Islands",
    "slug": "number-of-islands-lc200",
    "canonicalKey": "lc200",
    "link": "https://leetcode.com/problems/number-of-islands/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 80
  },
  {
    "title": "Clone Graph",
    "slug": "clone-graph-lc133",
    "canonicalKey": "lc133",
    "link": "https://leetcode.com/problems/clone-graph/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 81
  },
  {
    "title": "Max Area of Island",
    "slug": "max-area-of-island-lc695",
    "canonicalKey": "lc695",
    "link": "https://leetcode.com/problems/max-area-of-island/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 82
  },
  {
    "title": "Pacific Atlantic Water Flow",
    "slug": "pacific-atlantic-water-flow-lc417",
    "canonicalKey": "lc417",
    "link": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 83
  },
  {
    "title": "Surrounded Regions",
    "slug": "surrounded-regions-lc130",
    "canonicalKey": "lc130",
    "link": "https://leetcode.com/problems/surrounded-regions/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 84
  },
  {
    "title": "Rotting Oranges",
    "slug": "rotting-oranges-lc994",
    "canonicalKey": "lc994",
    "link": "https://leetcode.com/problems/rotting-oranges/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 85
  },
  {
    "title": "Walls and Gates",
    "slug": "walls-and-gates-lc286",
    "canonicalKey": "lc286",
    "link": "https://leetcode.com/problems/walls-and-gates/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 86
  },
  {
    "title": "Course Schedule",
    "slug": "course-schedule-lc207",
    "canonicalKey": "lc207",
    "link": "https://leetcode.com/problems/course-schedule/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 87
  },
  {
    "title": "Course Schedule II",
    "slug": "course-schedule-ii-lc210",
    "canonicalKey": "lc210",
    "link": "https://leetcode.com/problems/course-schedule-ii/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 88
  },
  {
    "title": "Graph Valid Tree",
    "slug": "graph-valid-tree-lc261",
    "canonicalKey": "lc261",
    "link": "https://leetcode.com/problems/graph-valid-tree/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 89
  },
  {
    "title": "Number of Connected Components",
    "slug": "number-of-connected-components-lc323",
    "canonicalKey": "lc323",
    "link": "https://leetcode.com/problems/number-of-connected-components/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 90
  },
  {
    "title": "Redundant Connection",
    "slug": "redundant-connection-lc684",
    "canonicalKey": "lc684",
    "link": "https://leetcode.com/problems/redundant-connection/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 91
  },
  {
    "title": "Word Ladder",
    "slug": "word-ladder-lc127",
    "canonicalKey": "lc127",
    "link": "https://leetcode.com/problems/word-ladder/",
    "difficulty": "Hard",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "neetcode150",
    "order": 92
  },
  {
    "title": "Reconstruct Itinerary",
    "slug": "reconstruct-itinerary-lc332",
    "canonicalKey": "lc332",
    "link": "https://leetcode.com/problems/reconstruct-itinerary/",
    "difficulty": "Hard",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 93
  },
  {
    "title": "Min Cost to Connect All Points",
    "slug": "min-cost-to-connect-all-points-lc1584",
    "canonicalKey": "lc1584",
    "link": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 94
  },
  {
    "title": "Network Delay Time",
    "slug": "network-delay-time-lc743",
    "canonicalKey": "lc743",
    "link": "https://leetcode.com/problems/network-delay-time/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 95
  },
  {
    "title": "Swim in Rising Water",
    "slug": "swim-in-rising-water-lc778",
    "canonicalKey": "lc778",
    "link": "https://leetcode.com/problems/swim-in-rising-water/",
    "difficulty": "Hard",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 96
  },
  {
    "title": "Alien Dictionary",
    "slug": "alien-dictionary-lc269",
    "canonicalKey": "lc269",
    "link": "https://leetcode.com/problems/alien-dictionary/",
    "difficulty": "Hard",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 97
  },
  {
    "title": "Cheapest Flights Within K Stops",
    "slug": "cheapest-flights-within-k-stops-lc787",
    "canonicalKey": "lc787",
    "link": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "neetcode150",
    "order": 98
  },
  {
    "title": "Climbing Stairs",
    "slug": "climbing-stairs-lc70",
    "canonicalKey": "lc70",
    "link": "https://leetcode.com/problems/climbing-stairs/",
    "difficulty": "Easy",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 99
  },
  {
    "title": "Min Cost Climbing Stairs",
    "slug": "min-cost-climbing-stairs-lc746",
    "canonicalKey": "lc746",
    "link": "https://leetcode.com/problems/min-cost-climbing-stairs/",
    "difficulty": "Easy",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 100
  },
  {
    "title": "House Robber",
    "slug": "house-robber-lc198",
    "canonicalKey": "lc198",
    "link": "https://leetcode.com/problems/house-robber/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 101
  },
  {
    "title": "House Robber II",
    "slug": "house-robber-ii-lc213",
    "canonicalKey": "lc213",
    "link": "https://leetcode.com/problems/house-robber-ii/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 102
  },
  {
    "title": "Longest Palindromic Substring",
    "slug": "longest-palindromic-substring-lc5",
    "canonicalKey": "lc5",
    "link": "https://leetcode.com/problems/longest-palindromic-substring/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 103
  },
  {
    "title": "Palindromic Substrings",
    "slug": "palindromic-substrings-lc647",
    "canonicalKey": "lc647",
    "link": "https://leetcode.com/problems/palindromic-substrings/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 104
  },
  {
    "title": "Decode Ways",
    "slug": "decode-ways-lc91",
    "canonicalKey": "lc91",
    "link": "https://leetcode.com/problems/decode-ways/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 105
  },
  {
    "title": "Coin Change",
    "slug": "coin-change-lc322",
    "canonicalKey": "lc322",
    "link": "https://leetcode.com/problems/coin-change/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 106
  },
  {
    "title": "Maximum Product Subarray",
    "slug": "maximum-product-subarray-lc152",
    "canonicalKey": "lc152",
    "link": "https://leetcode.com/problems/maximum-product-subarray/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 107
  },
  {
    "title": "Word Break",
    "slug": "word-break-lc139",
    "canonicalKey": "lc139",
    "link": "https://leetcode.com/problems/word-break/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 108
  },
  {
    "title": "Longest Increasing Subsequence",
    "slug": "longest-increasing-subsequence-lc300",
    "canonicalKey": "lc300",
    "link": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 109
  },
  {
    "title": "Partition Equal Subset Sum",
    "slug": "partition-equal-subset-sum-lc416",
    "canonicalKey": "lc416",
    "link": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 110
  },
  {
    "title": "Unique Paths",
    "slug": "unique-paths-lc62",
    "canonicalKey": "lc62",
    "link": "https://leetcode.com/problems/unique-paths/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 111
  },
  {
    "title": "Longest Common Subsequence",
    "slug": "longest-common-subsequence-lc1143",
    "canonicalKey": "lc1143",
    "link": "https://leetcode.com/problems/longest-common-subsequence/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 112
  },
  {
    "title": "Best Time to Buy and Sell Stock with Cooldown",
    "slug": "best-time-to-buy-and-sell-stock-with-cooldown-lc309",
    "canonicalKey": "lc309",
    "link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 113
  },
  {
    "title": "Coin Change II",
    "slug": "coin-change-ii-lc518",
    "canonicalKey": "lc518",
    "link": "https://leetcode.com/problems/coin-change-ii/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 114
  },
  {
    "title": "Target Sum",
    "slug": "target-sum-lc494",
    "canonicalKey": "lc494",
    "link": "https://leetcode.com/problems/target-sum/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 115
  },
  {
    "title": "Interleaving String",
    "slug": "interleaving-string-lc97",
    "canonicalKey": "lc97",
    "link": "https://leetcode.com/problems/interleaving-string/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 116
  },
  {
    "title": "Longest Increasing Path in a Matrix",
    "slug": "longest-increasing-path-in-a-matrix-lc329",
    "canonicalKey": "lc329",
    "link": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 117
  },
  {
    "title": "Distinct Subsequences",
    "slug": "distinct-subsequences-lc115",
    "canonicalKey": "lc115",
    "link": "https://leetcode.com/problems/distinct-subsequences/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 118
  },
  {
    "title": "Edit Distance",
    "slug": "edit-distance-lc72",
    "canonicalKey": "lc72",
    "link": "https://leetcode.com/problems/edit-distance/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 119
  },
  {
    "title": "Burst Balloons",
    "slug": "burst-balloons-lc312",
    "canonicalKey": "lc312",
    "link": "https://leetcode.com/problems/burst-balloons/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 120
  },
  {
    "title": "Regular Expression Matching",
    "slug": "regular-expression-matching-lc10",
    "canonicalKey": "lc10",
    "link": "https://leetcode.com/problems/regular-expression-matching/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "neetcode150",
    "order": 121
  },
  {
    "title": "Maximum Subarray",
    "slug": "maximum-subarray-lc53",
    "canonicalKey": "lc53",
    "link": "https://leetcode.com/problems/maximum-subarray/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 122
  },
  {
    "title": "Jump Game",
    "slug": "jump-game-lc55",
    "canonicalKey": "lc55",
    "link": "https://leetcode.com/problems/jump-game/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 123
  },
  {
    "title": "Jump Game II",
    "slug": "jump-game-ii-lc45",
    "canonicalKey": "lc45",
    "link": "https://leetcode.com/problems/jump-game-ii/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 124
  },
  {
    "title": "Gas Station",
    "slug": "gas-station-lc134",
    "canonicalKey": "lc134",
    "link": "https://leetcode.com/problems/gas-station/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 125
  },
  {
    "title": "Hand of Straights",
    "slug": "hand-of-straights-lc846",
    "canonicalKey": "lc846",
    "link": "https://leetcode.com/problems/hand-of-straights/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 126
  },
  {
    "title": "Merge Triplets to Form Target Triplet",
    "slug": "merge-triplets-to-form-target-triplet-lc1899",
    "canonicalKey": "lc1899",
    "link": "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 127
  },
  {
    "title": "Partition Labels",
    "slug": "partition-labels-lc763",
    "canonicalKey": "lc763",
    "link": "https://leetcode.com/problems/partition-labels/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 128
  },
  {
    "title": "Valid Parenthesis String",
    "slug": "valid-parenthesis-string-lc678",
    "canonicalKey": "lc678",
    "link": "https://leetcode.com/problems/valid-parenthesis-string/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "neetcode150",
    "order": 129
  },
  {
    "title": "Insert Interval",
    "slug": "insert-interval-lc57",
    "canonicalKey": "lc57",
    "link": "https://leetcode.com/problems/insert-interval/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 130
  },
  {
    "title": "Merge Intervals",
    "slug": "merge-intervals-lc56",
    "canonicalKey": "lc56",
    "link": "https://leetcode.com/problems/merge-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 131
  },
  {
    "title": "Non-Overlapping Intervals",
    "slug": "non-overlapping-intervals-lc435",
    "canonicalKey": "lc435",
    "link": "https://leetcode.com/problems/non-overlapping-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 132
  },
  {
    "title": "Meeting Rooms",
    "slug": "meeting-rooms-lc252",
    "canonicalKey": "lc252",
    "link": "https://leetcode.com/problems/meeting-rooms/",
    "difficulty": "Easy",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 133
  },
  {
    "title": "Meeting Rooms II",
    "slug": "meeting-rooms-ii-lc253",
    "canonicalKey": "lc253",
    "link": "https://leetcode.com/problems/meeting-rooms-ii/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 134
  },
  {
    "title": "Minimum Interval to Include Each Query",
    "slug": "minimum-interval-to-include-each-query-lc1851",
    "canonicalKey": "lc1851",
    "link": "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
    "difficulty": "Hard",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "neetcode150",
    "order": 135
  },
  {
    "title": "Rotate Image",
    "slug": "rotate-image-lc48",
    "canonicalKey": "lc48",
    "link": "https://leetcode.com/problems/rotate-image/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 136
  },
  {
    "title": "Spiral Matrix",
    "slug": "spiral-matrix-lc54",
    "canonicalKey": "lc54",
    "link": "https://leetcode.com/problems/spiral-matrix/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 137
  },
  {
    "title": "Set Matrix Zeroes",
    "slug": "set-matrix-zeroes-lc73",
    "canonicalKey": "lc73",
    "link": "https://leetcode.com/problems/set-matrix-zeroes/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 138
  },
  {
    "title": "Happy Number",
    "slug": "happy-number-lc202",
    "canonicalKey": "lc202",
    "link": "https://leetcode.com/problems/happy-number/",
    "difficulty": "Easy",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 139
  },
  {
    "title": "Plus One",
    "slug": "plus-one-lc66",
    "canonicalKey": "lc66",
    "link": "https://leetcode.com/problems/plus-one/",
    "difficulty": "Easy",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 140
  },
  {
    "title": "Pow(x, n)",
    "slug": "pow-x-n-lc50",
    "canonicalKey": "lc50",
    "link": "https://leetcode.com/problems/pow-x-n/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 141
  },
  {
    "title": "Multiply Strings",
    "slug": "multiply-strings-lc43",
    "canonicalKey": "lc43",
    "link": "https://leetcode.com/problems/multiply-strings/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 142
  },
  {
    "title": "Detect Squares",
    "slug": "detect-squares-lc2013",
    "canonicalKey": "lc2013",
    "link": "https://leetcode.com/problems/detect-squares/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "neetcode150",
    "order": 143
  },
  {
    "title": "Single Number",
    "slug": "single-number-lc136",
    "canonicalKey": "lc136",
    "link": "https://leetcode.com/problems/single-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 144
  },
  {
    "title": "Number of 1 Bits",
    "slug": "number-of-1-bits-lc191",
    "canonicalKey": "lc191",
    "link": "https://leetcode.com/problems/number-of-1-bits/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 145
  },
  {
    "title": "Counting Bits",
    "slug": "counting-bits-lc338",
    "canonicalKey": "lc338",
    "link": "https://leetcode.com/problems/counting-bits/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 146
  },
  {
    "title": "Reverse Bits",
    "slug": "reverse-bits-lc190",
    "canonicalKey": "lc190",
    "link": "https://leetcode.com/problems/reverse-bits/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 147
  },
  {
    "title": "Missing Number",
    "slug": "missing-number-lc268",
    "canonicalKey": "lc268",
    "link": "https://leetcode.com/problems/missing-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 148
  },
  {
    "title": "Sum of Two Integers",
    "slug": "sum-of-two-integers-lc371",
    "canonicalKey": "lc371",
    "link": "https://leetcode.com/problems/sum-of-two-integers/",
    "difficulty": "Medium",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 149
  },
  {
    "title": "Reverse Integer",
    "slug": "reverse-integer-lc7",
    "canonicalKey": "lc7",
    "link": "https://leetcode.com/problems/reverse-integer/",
    "difficulty": "Medium",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "neetcode150",
    "order": 150
  }
];
