module.exports = [
  {
    "title": "Two Sum",
    "slug": "two-sum-lc1",
    "canonicalKey": "lc1",
    "link": "https://leetcode.com/problems/two-sum/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 1
  },
  {
    "title": "Sort an Array of 0s, 1s and 2s",
    "slug": "sort-an-array-of-0s-1s-and-2s-lc75",
    "canonicalKey": "lc75",
    "link": "https://leetcode.com/problems/sort-colors/",
    "difficulty": "Medium",
    "category": "Basics & Arrays",
    "pattern": "Basics & Arrays",
    "sheet": "striverA2Z",
    "order": 2
  },
  {
    "title": "Majority Element",
    "slug": "majority-element-lc169",
    "canonicalKey": "lc169",
    "link": "https://leetcode.com/problems/majority-element/",
    "difficulty": "Unknown",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 3
  },
  {
    "title": "Maximum Subarray",
    "slug": "maximum-subarray-lc53",
    "canonicalKey": "lc53",
    "link": "https://leetcode.com/problems/maximum-subarray/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "striverA2Z",
    "order": 4
  },
  {
    "title": "Best Time to Buy and Sell Stock",
    "slug": "best-time-to-buy-and-sell-stock-lc121",
    "canonicalKey": "lc121",
    "link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 5
  },
  {
    "title": "Rotate Array",
    "slug": "rotate-array-lc189",
    "canonicalKey": "lc189",
    "link": "https://leetcode.com/problems/rotate-array/",
    "difficulty": "Unknown",
    "category": "Basics & Arrays",
    "pattern": "Basics & Arrays",
    "sheet": "striverA2Z",
    "order": 6
  },
  {
    "title": "Next Permutation",
    "slug": "next-permutation-lc31",
    "canonicalKey": "lc31",
    "link": "https://leetcode.com/problems/next-permutation/",
    "difficulty": "Unknown",
    "category": "Basics & Arrays",
    "pattern": "Basics & Arrays",
    "sheet": "striverA2Z",
    "order": 7
  },
  {
    "title": "Leaders in an Array",
    "slug": "leaders-in-an-array-gfg",
    "canonicalKey": "gfg-leaders-in-an-array",
    "link": "https://www.geeksforgeeks.org/leaders-in-an-array/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 8
  },
  {
    "title": "Longest Consecutive Sequence",
    "slug": "longest-consecutive-sequence-lc128",
    "canonicalKey": "lc128",
    "link": "https://leetcode.com/problems/longest-consecutive-sequence/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 9
  },
  {
    "title": "Set Matrix Zeroes",
    "slug": "set-matrix-zeroes-lc73",
    "canonicalKey": "lc73",
    "link": "https://leetcode.com/problems/set-matrix-zeroes/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "striverA2Z",
    "order": 10
  },
  {
    "title": "Rotate Image",
    "slug": "rotate-image-lc48",
    "canonicalKey": "lc48",
    "link": "https://leetcode.com/problems/rotate-image/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "striverA2Z",
    "order": 11
  },
  {
    "title": "Spiral Matrix",
    "slug": "spiral-matrix-lc54",
    "canonicalKey": "lc54",
    "link": "https://leetcode.com/problems/spiral-matrix/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "striverA2Z",
    "order": 12
  },
  {
    "title": "3Sum",
    "slug": "3sum-lc15",
    "canonicalKey": "lc15",
    "link": "https://leetcode.com/problems/3sum/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 13
  },
  {
    "title": "4Sum",
    "slug": "4sum-lc18",
    "canonicalKey": "lc18",
    "link": "https://leetcode.com/problems/4sum/",
    "difficulty": "Unknown",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striverA2Z",
    "order": 14
  },
  {
    "title": "Count Subarrays with Given Sum",
    "slug": "count-subarrays-with-given-sum-lc560",
    "canonicalKey": "lc560",
    "link": "https://leetcode.com/problems/subarray-sum-equals-k/",
    "difficulty": "Unknown",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 15
  },
  {
    "title": "Pascal's Triangle",
    "slug": "pascal-s-triangle-lc118",
    "canonicalKey": "lc118",
    "link": "https://leetcode.com/problems/pascals-triangle/",
    "difficulty": "Unknown",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 16
  },
  {
    "title": "Merge Sorted Array",
    "slug": "merge-sorted-array-lc88",
    "canonicalKey": "lc88",
    "link": "https://leetcode.com/problems/merge-sorted-array/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 17
  },
  {
    "title": "Find the Duplicate Number",
    "slug": "find-the-duplicate-number-lc287",
    "canonicalKey": "lc287",
    "link": "https://leetcode.com/problems/find-the-duplicate-number/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 18
  },
  {
    "title": "Missing Number",
    "slug": "missing-number-lc268",
    "canonicalKey": "lc268",
    "link": "https://leetcode.com/problems/missing-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "striverA2Z",
    "order": 19
  },
  {
    "title": "Maximum Product Subarray",
    "slug": "maximum-product-subarray-lc152",
    "canonicalKey": "lc152",
    "link": "https://leetcode.com/problems/maximum-product-subarray/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 20
  },
  {
    "title": "Two Sum II",
    "slug": "two-sum-ii-lc167",
    "canonicalKey": "lc167",
    "link": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striverA2Z",
    "order": 21
  },
  {
    "title": "Valid Palindrome",
    "slug": "valid-palindrome-lc125",
    "canonicalKey": "lc125",
    "link": "https://leetcode.com/problems/valid-palindrome/",
    "difficulty": "Easy",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striverA2Z",
    "order": 22
  },
  {
    "title": "Longest Substring Without Repeating Characters",
    "slug": "longest-substring-without-repeating-characters-lc3",
    "canonicalKey": "lc3",
    "link": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striverA2Z",
    "order": 23
  },
  {
    "title": "Longest Repeating Character Replacement",
    "slug": "longest-repeating-character-replacement-lc424",
    "canonicalKey": "lc424",
    "link": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striverA2Z",
    "order": 24
  },
  {
    "title": "Minimum Window Substring",
    "slug": "minimum-window-substring-lc76",
    "canonicalKey": "lc76",
    "link": "https://leetcode.com/problems/minimum-window-substring/",
    "difficulty": "Hard",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striverA2Z",
    "order": 25
  },
  {
    "title": "Remove Duplicates from Sorted Array",
    "slug": "remove-duplicates-from-sorted-array-lc26",
    "canonicalKey": "lc26",
    "link": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    "difficulty": "Easy",
    "category": "Two Pointers & Sliding Window",
    "pattern": "Two Pointers & Sliding Window",
    "sheet": "striverA2Z",
    "order": 26
  },
  {
    "title": "Move Zeroes",
    "slug": "move-zeroes-lc283",
    "canonicalKey": "lc283",
    "link": "https://leetcode.com/problems/move-zeroes/",
    "difficulty": "Easy",
    "category": "Two Pointers & Sliding Window",
    "pattern": "Two Pointers & Sliding Window",
    "sheet": "striverA2Z",
    "order": 27
  },
  {
    "title": "Container With Most Water",
    "slug": "container-with-most-water-lc11",
    "canonicalKey": "lc11",
    "link": "https://leetcode.com/problems/container-with-most-water/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striverA2Z",
    "order": 28
  },
  {
    "title": "Trapping Rain Water",
    "slug": "trapping-rain-water-lc42",
    "canonicalKey": "lc42",
    "link": "https://leetcode.com/problems/trapping-rain-water/",
    "difficulty": "Hard",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striverA2Z",
    "order": 29
  },
  {
    "title": "Binary Search",
    "slug": "binary-search-lc704",
    "canonicalKey": "lc704",
    "link": "https://leetcode.com/problems/binary-search/",
    "difficulty": "Easy",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striverA2Z",
    "order": 30
  },
  {
    "title": "Search in Rotated Sorted Array",
    "slug": "search-in-rotated-sorted-array-lc33",
    "canonicalKey": "lc33",
    "link": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 31
  },
  {
    "title": "Find Minimum in Rotated Sorted Array",
    "slug": "find-minimum-in-rotated-sorted-array-lc153",
    "canonicalKey": "lc153",
    "link": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striverA2Z",
    "order": 32
  },
  {
    "title": "Search a 2D Matrix",
    "slug": "search-a-2d-matrix-lc74",
    "canonicalKey": "lc74",
    "link": "https://leetcode.com/problems/search-a-2d-matrix/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striverA2Z",
    "order": 33
  },
  {
    "title": "Koko Eating Bananas",
    "slug": "koko-eating-bananas-lc875",
    "canonicalKey": "lc875",
    "link": "https://leetcode.com/problems/koko-eating-bananas/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striverA2Z",
    "order": 34
  },
  {
    "title": "Find Peak Element",
    "slug": "find-peak-element-lc162",
    "canonicalKey": "lc162",
    "link": "https://leetcode.com/problems/find-peak-element/",
    "difficulty": "Unknown",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striverA2Z",
    "order": 35
  },
  {
    "title": "Median of Two Sorted Arrays",
    "slug": "median-of-two-sorted-arrays-lc4",
    "canonicalKey": "lc4",
    "link": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "difficulty": "Hard",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striverA2Z",
    "order": 36
  },
  {
    "title": "Reverse Linked List",
    "slug": "reverse-linked-list-lc206",
    "canonicalKey": "lc206",
    "link": "https://leetcode.com/problems/reverse-linked-list/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 37
  },
  {
    "title": "Middle of the Linked List",
    "slug": "middle-of-the-linked-list-lc876",
    "canonicalKey": "lc876",
    "link": "https://leetcode.com/problems/middle-of-the-linked-list/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 38
  },
  {
    "title": "Merge Two Sorted Lists",
    "slug": "merge-two-sorted-lists-lc21",
    "canonicalKey": "lc21",
    "link": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 39
  },
  {
    "title": "Remove Nth Node From End",
    "slug": "remove-nth-node-from-end-lc19",
    "canonicalKey": "lc19",
    "link": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 40
  },
  {
    "title": "Linked List Cycle",
    "slug": "linked-list-cycle-lc141",
    "canonicalKey": "lc141",
    "link": "https://leetcode.com/problems/linked-list-cycle/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 41
  },
  {
    "title": "Intersection of Two Linked Lists",
    "slug": "intersection-of-two-linked-lists-lc160",
    "canonicalKey": "lc160",
    "link": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    "difficulty": "Unknown",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 42
  },
  {
    "title": "Palindrome Linked List",
    "slug": "palindrome-linked-list-lc234",
    "canonicalKey": "lc234",
    "link": "https://leetcode.com/problems/palindrome-linked-list/",
    "difficulty": "Unknown",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 43
  },
  {
    "title": "Add Two Numbers",
    "slug": "add-two-numbers-lc2",
    "canonicalKey": "lc2",
    "link": "https://leetcode.com/problems/add-two-numbers/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 44
  },
  {
    "title": "Copy List with Random Pointer",
    "slug": "copy-list-with-random-pointer-lc138",
    "canonicalKey": "lc138",
    "link": "https://leetcode.com/problems/copy-list-with-random-pointer/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 45
  },
  {
    "title": "Rotate List",
    "slug": "rotate-list-lc61",
    "canonicalKey": "lc61",
    "link": "https://leetcode.com/problems/rotate-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 46
  },
  {
    "title": "Flatten a Multilevel Doubly Linked List",
    "slug": "flatten-a-multilevel-doubly-linked-list-lc430",
    "canonicalKey": "lc430",
    "link": "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 47
  },
  {
    "title": "Reverse Nodes in K-Group",
    "slug": "reverse-nodes-in-k-group-lc25",
    "canonicalKey": "lc25",
    "link": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "difficulty": "Hard",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striverA2Z",
    "order": 48
  },
  {
    "title": "Valid Parentheses",
    "slug": "valid-parentheses-lc20",
    "canonicalKey": "lc20",
    "link": "https://leetcode.com/problems/valid-parentheses/",
    "difficulty": "Easy",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striverA2Z",
    "order": 49
  },
  {
    "title": "Min Stack",
    "slug": "min-stack-lc155",
    "canonicalKey": "lc155",
    "link": "https://leetcode.com/problems/min-stack/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striverA2Z",
    "order": 50
  },
  {
    "title": "Next Greater Element I",
    "slug": "next-greater-element-i-lc496",
    "canonicalKey": "lc496",
    "link": "https://leetcode.com/problems/next-greater-element-i/",
    "difficulty": "Easy",
    "category": "Stack & Queue",
    "pattern": "Stack & Queue",
    "sheet": "striverA2Z",
    "order": 51
  },
  {
    "title": "Next Greater Element II",
    "slug": "next-greater-element-ii-lc503",
    "canonicalKey": "lc503",
    "link": "https://leetcode.com/problems/next-greater-element-ii/",
    "difficulty": "Medium",
    "category": "Stack & Queue",
    "pattern": "Stack & Queue",
    "sheet": "striverA2Z",
    "order": 52
  },
  {
    "title": "Daily Temperatures",
    "slug": "daily-temperatures-lc739",
    "canonicalKey": "lc739",
    "link": "https://leetcode.com/problems/daily-temperatures/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striverA2Z",
    "order": 53
  },
  {
    "title": "Largest Rectangle in Histogram",
    "slug": "largest-rectangle-in-histogram-lc84",
    "canonicalKey": "lc84",
    "link": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "difficulty": "Hard",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striverA2Z",
    "order": 54
  },
  {
    "title": "Sliding Window Maximum",
    "slug": "sliding-window-maximum-lc239",
    "canonicalKey": "lc239",
    "link": "https://leetcode.com/problems/sliding-window-maximum/",
    "difficulty": "Hard",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "striverA2Z",
    "order": 55
  },
  {
    "title": "Implement Queue using Stacks",
    "slug": "implement-queue-using-stacks-lc232",
    "canonicalKey": "lc232",
    "link": "https://leetcode.com/problems/implement-queue-using-stacks/",
    "difficulty": "Easy",
    "category": "Stack & Queue",
    "pattern": "Stack & Queue",
    "sheet": "striverA2Z",
    "order": 56
  },
  {
    "title": "Implement Stack using Queues",
    "slug": "implement-stack-using-queues-lc225",
    "canonicalKey": "lc225",
    "link": "https://leetcode.com/problems/implement-stack-using-queues/",
    "difficulty": "Easy",
    "category": "Stack & Queue",
    "pattern": "Stack & Queue",
    "sheet": "striverA2Z",
    "order": 57
  },
  {
    "title": "Binary Tree Inorder Traversal",
    "slug": "binary-tree-inorder-traversal-lc94",
    "canonicalKey": "lc94",
    "link": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    "difficulty": "Unknown",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 58
  },
  {
    "title": "Binary Tree Preorder Traversal",
    "slug": "binary-tree-preorder-traversal-lc144",
    "canonicalKey": "lc144",
    "link": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 59
  },
  {
    "title": "Binary Tree Postorder Traversal",
    "slug": "binary-tree-postorder-traversal-lc145",
    "canonicalKey": "lc145",
    "link": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 60
  },
  {
    "title": "Maximum Depth of Binary Tree",
    "slug": "maximum-depth-of-binary-tree-lc104",
    "canonicalKey": "lc104",
    "link": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 61
  },
  {
    "title": "Same Tree",
    "slug": "same-tree-lc100",
    "canonicalKey": "lc100",
    "link": "https://leetcode.com/problems/same-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 62
  },
  {
    "title": "Invert Binary Tree",
    "slug": "invert-binary-tree-lc226",
    "canonicalKey": "lc226",
    "link": "https://leetcode.com/problems/invert-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 63
  },
  {
    "title": "Symmetric Tree",
    "slug": "symmetric-tree-lc101",
    "canonicalKey": "lc101",
    "link": "https://leetcode.com/problems/symmetric-tree/",
    "difficulty": "Unknown",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 64
  },
  {
    "title": "Balanced Binary Tree",
    "slug": "balanced-binary-tree-lc110",
    "canonicalKey": "lc110",
    "link": "https://leetcode.com/problems/balanced-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 65
  },
  {
    "title": "Diameter of Binary Tree",
    "slug": "diameter-of-binary-tree-lc543",
    "canonicalKey": "lc543",
    "link": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 66
  },
  {
    "title": "Binary Tree Level Order Traversal",
    "slug": "binary-tree-level-order-traversal-lc102",
    "canonicalKey": "lc102",
    "link": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 67
  },
  {
    "title": "Zigzag Level Order Traversal",
    "slug": "zigzag-level-order-traversal-lc103",
    "canonicalKey": "lc103",
    "link": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 68
  },
  {
    "title": "Lowest Common Ancestor of a Binary Tree",
    "slug": "lowest-common-ancestor-of-a-binary-tree-lc236",
    "canonicalKey": "lc236",
    "link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    "difficulty": "Unknown",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 69
  },
  {
    "title": "Binary Tree Maximum Path Sum",
    "slug": "binary-tree-maximum-path-sum-lc124",
    "canonicalKey": "lc124",
    "link": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 70
  },
  {
    "title": "Serialize and Deserialize Binary Tree",
    "slug": "serialize-and-deserialize-binary-tree-lc297",
    "canonicalKey": "lc297",
    "link": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 71
  },
  {
    "title": "Construct Binary Tree from Preorder and Inorder",
    "slug": "construct-binary-tree-from-preorder-and-inorder-lc105",
    "canonicalKey": "lc105",
    "link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 72
  },
  {
    "title": "Validate Binary Search Tree",
    "slug": "validate-binary-search-tree-lc98",
    "canonicalKey": "lc98",
    "link": "https://leetcode.com/problems/validate-binary-search-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 73
  },
  {
    "title": "Kth Smallest Element in a BST",
    "slug": "kth-smallest-element-in-a-bst-lc230",
    "canonicalKey": "lc230",
    "link": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 74
  },
  {
    "title": "Lowest Common Ancestor of a BST",
    "slug": "lowest-common-ancestor-of-a-bst-lc235",
    "canonicalKey": "lc235",
    "link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striverA2Z",
    "order": 75
  },
  {
    "title": "Number of Islands",
    "slug": "number-of-islands-lc200",
    "canonicalKey": "lc200",
    "link": "https://leetcode.com/problems/number-of-islands/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 76
  },
  {
    "title": "Flood Fill",
    "slug": "flood-fill-lc733",
    "canonicalKey": "lc733",
    "link": "https://leetcode.com/problems/flood-fill/",
    "difficulty": "Unknown",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 77
  },
  {
    "title": "Clone Graph",
    "slug": "clone-graph-lc133",
    "canonicalKey": "lc133",
    "link": "https://leetcode.com/problems/clone-graph/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 78
  },
  {
    "title": "Course Schedule",
    "slug": "course-schedule-lc207",
    "canonicalKey": "lc207",
    "link": "https://leetcode.com/problems/course-schedule/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 79
  },
  {
    "title": "Course Schedule II",
    "slug": "course-schedule-ii-lc210",
    "canonicalKey": "lc210",
    "link": "https://leetcode.com/problems/course-schedule-ii/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 80
  },
  {
    "title": "Number of Provinces",
    "slug": "number-of-provinces-lc547",
    "canonicalKey": "lc547",
    "link": "https://leetcode.com/problems/number-of-provinces/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 81
  },
  {
    "title": "Rotting Oranges",
    "slug": "rotting-oranges-lc994",
    "canonicalKey": "lc994",
    "link": "https://leetcode.com/problems/rotting-oranges/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 82
  },
  {
    "title": "Word Ladder",
    "slug": "word-ladder-lc127",
    "canonicalKey": "lc127",
    "link": "https://leetcode.com/problems/word-ladder/",
    "difficulty": "Hard",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 83
  },
  {
    "title": "Surrounded Regions",
    "slug": "surrounded-regions-lc130",
    "canonicalKey": "lc130",
    "link": "https://leetcode.com/problems/surrounded-regions/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 84
  },
  {
    "title": "Pacific Atlantic Water Flow",
    "slug": "pacific-atlantic-water-flow-lc417",
    "canonicalKey": "lc417",
    "link": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 85
  },
  {
    "title": "Number of Enclaves",
    "slug": "number-of-enclaves-lc1020",
    "canonicalKey": "lc1020",
    "link": "https://leetcode.com/problems/number-of-enclaves/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 86
  },
  {
    "title": "Is Graph Bipartite?",
    "slug": "is-graph-bipartite-lc785",
    "canonicalKey": "lc785",
    "link": "https://leetcode.com/problems/is-graph-bipartite/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 87
  },
  {
    "title": "Detect Cycle in Undirected Graph",
    "slug": "detect-cycle-in-undirected-graph-lc684",
    "canonicalKey": "lc684",
    "link": "https://leetcode.com/problems/redundant-connection/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 88
  },
  {
    "title": "Detect Cycle in Directed Graph",
    "slug": "detect-cycle-in-directed-graph-lc207",
    "canonicalKey": "lc207",
    "link": "https://leetcode.com/problems/course-schedule/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 89
  },
  {
    "title": "Topological Sort",
    "slug": "topological-sort-lc210",
    "canonicalKey": "lc210",
    "link": "https://leetcode.com/problems/course-schedule-ii/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 90
  },
  {
    "title": "Dijkstra's Algorithm",
    "slug": "dijkstra-s-algorithm-lc743",
    "canonicalKey": "lc743",
    "link": "https://leetcode.com/problems/network-delay-time/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "striverA2Z",
    "order": 91
  },
  {
    "title": "Bellman-Ford",
    "slug": "bellman-ford-lc787",
    "canonicalKey": "lc787",
    "link": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "striverA2Z",
    "order": 92
  },
  {
    "title": "Floyd-Warshall",
    "slug": "floyd-warshall-lc1334",
    "canonicalKey": "lc1334",
    "link": "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striverA2Z",
    "order": 93
  },
  {
    "title": "Minimum Spanning Tree - Prim's",
    "slug": "minimum-spanning-tree-prim-s-lc1584",
    "canonicalKey": "lc1584",
    "link": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "striverA2Z",
    "order": 94
  },
  {
    "title": "Minimum Spanning Tree - Kruskal's",
    "slug": "minimum-spanning-tree-kruskal-s-lc1584",
    "canonicalKey": "lc1584",
    "link": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    "difficulty": "Medium",
    "category": "Advanced Graphs",
    "pattern": "Advanced Graphs",
    "sheet": "striverA2Z",
    "order": 95
  },
  {
    "title": "Climbing Stairs",
    "slug": "climbing-stairs-lc70",
    "canonicalKey": "lc70",
    "link": "https://leetcode.com/problems/climbing-stairs/",
    "difficulty": "Easy",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 96
  },
  {
    "title": "Frog Jump",
    "slug": "frog-jump-lc403",
    "canonicalKey": "lc403",
    "link": "https://leetcode.com/problems/frog-jump/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 97
  },
  {
    "title": "House Robber",
    "slug": "house-robber-lc198",
    "canonicalKey": "lc198",
    "link": "https://leetcode.com/problems/house-robber/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 98
  },
  {
    "title": "House Robber II",
    "slug": "house-robber-ii-lc213",
    "canonicalKey": "lc213",
    "link": "https://leetcode.com/problems/house-robber-ii/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 99
  },
  {
    "title": "Unique Paths",
    "slug": "unique-paths-lc62",
    "canonicalKey": "lc62",
    "link": "https://leetcode.com/problems/unique-paths/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 100
  },
  {
    "title": "Unique Paths II",
    "slug": "unique-paths-ii-lc63",
    "canonicalKey": "lc63",
    "link": "https://leetcode.com/problems/unique-paths-ii/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 101
  },
  {
    "title": "Minimum Path Sum",
    "slug": "minimum-path-sum-lc64",
    "canonicalKey": "lc64",
    "link": "https://leetcode.com/problems/minimum-path-sum/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 102
  },
  {
    "title": "Triangle",
    "slug": "triangle-lc120",
    "canonicalKey": "lc120",
    "link": "https://leetcode.com/problems/triangle/",
    "difficulty": "Unknown",
    "category": "2-D DP",
    "pattern": "2-D DP",
    "sheet": "striverA2Z",
    "order": 103
  },
  {
    "title": "Partition Equal Subset Sum",
    "slug": "partition-equal-subset-sum-lc416",
    "canonicalKey": "lc416",
    "link": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 104
  },
  {
    "title": "0/1 Knapsack",
    "slug": "0-1-knapsack-gfg",
    "canonicalKey": "gfg-0-1-knapsack",
    "link": "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 105
  },
  {
    "title": "Coin Change",
    "slug": "coin-change-lc322",
    "canonicalKey": "lc322",
    "link": "https://leetcode.com/problems/coin-change/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 106
  },
  {
    "title": "Longest Common Subsequence",
    "slug": "longest-common-subsequence-lc1143",
    "canonicalKey": "lc1143",
    "link": "https://leetcode.com/problems/longest-common-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 107
  },
  {
    "title": "Longest Palindromic Subsequence",
    "slug": "longest-palindromic-subsequence-lc516",
    "canonicalKey": "lc516",
    "link": "https://leetcode.com/problems/longest-palindromic-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 108
  },
  {
    "title": "Edit Distance",
    "slug": "edit-distance-lc72",
    "canonicalKey": "lc72",
    "link": "https://leetcode.com/problems/edit-distance/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 109
  },
  {
    "title": "Distinct Subsequences",
    "slug": "distinct-subsequences-lc115",
    "canonicalKey": "lc115",
    "link": "https://leetcode.com/problems/distinct-subsequences/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "striverA2Z",
    "order": 110
  },
  {
    "title": "Wildcard Matching",
    "slug": "wildcard-matching-lc44",
    "canonicalKey": "lc44",
    "link": "https://leetcode.com/problems/wildcard-matching/",
    "difficulty": "Hard",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 111
  },
  {
    "title": "Palindrome Partitioning II",
    "slug": "palindrome-partitioning-ii-lc132",
    "canonicalKey": "lc132",
    "link": "https://leetcode.com/problems/palindrome-partitioning-ii/",
    "difficulty": "Hard",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striverA2Z",
    "order": 112
  },
  {
    "title": "N-Queens",
    "slug": "n-queens-lc51",
    "canonicalKey": "lc51",
    "link": "https://leetcode.com/problems/n-queens/",
    "difficulty": "Hard",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 113
  },
  {
    "title": "Sudoku Solver",
    "slug": "sudoku-solver-lc37",
    "canonicalKey": "lc37",
    "link": "https://leetcode.com/problems/sudoku-solver/",
    "difficulty": "Unknown",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 114
  },
  {
    "title": "Word Search",
    "slug": "word-search-lc79",
    "canonicalKey": "lc79",
    "link": "https://leetcode.com/problems/word-search/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 115
  },
  {
    "title": "Combination Sum",
    "slug": "combination-sum-lc39",
    "canonicalKey": "lc39",
    "link": "https://leetcode.com/problems/combination-sum/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 116
  },
  {
    "title": "Subsets",
    "slug": "subsets-lc78",
    "canonicalKey": "lc78",
    "link": "https://leetcode.com/problems/subsets/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 117
  },
  {
    "title": "Permutations",
    "slug": "permutations-lc46",
    "canonicalKey": "lc46",
    "link": "https://leetcode.com/problems/permutations/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striverA2Z",
    "order": 118
  }
];
