module.exports = [
  {
    "title": "Two Sum",
    "slug": "two-sum-lc1-79",
    "canonicalKey": "lc1",
    "link": "https://leetcode.com/problems/two-sum/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 1
  },
  {
    "title": "Best Time to Buy and Sell Stock",
    "slug": "best-time-to-buy-and-sell-stock-lc121-79",
    "canonicalKey": "lc121",
    "link": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 2
  },
  {
    "title": "Contains Duplicate",
    "slug": "contains-duplicate-lc217-79",
    "canonicalKey": "lc217",
    "link": "https://leetcode.com/problems/contains-duplicate/",
    "difficulty": "Easy",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 3
  },
  {
    "title": "Product of Array Except Self",
    "slug": "product-of-array-except-self-lc238-79",
    "canonicalKey": "lc238",
    "link": "https://leetcode.com/problems/product-of-array-except-self/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 4
  },
  {
    "title": "Maximum Subarray",
    "slug": "maximum-subarray-lc53-79",
    "canonicalKey": "lc53",
    "link": "https://leetcode.com/problems/maximum-subarray/",
    "difficulty": "Medium",
    "category": "Greedy",
    "pattern": "Greedy",
    "sheet": "striver79",
    "order": 5
  },
  {
    "title": "Maximum Product Subarray",
    "slug": "maximum-product-subarray-lc152-79",
    "canonicalKey": "lc152",
    "link": "https://leetcode.com/problems/maximum-product-subarray/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 6
  },
  {
    "title": "Find Minimum in Rotated Sorted Array",
    "slug": "find-minimum-in-rotated-sorted-array-lc153-79",
    "canonicalKey": "lc153",
    "link": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 7
  },
  {
    "title": "Search in Rotated Sorted Array",
    "slug": "search-in-rotated-sorted-array-lc33-79",
    "canonicalKey": "lc33",
    "link": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 8
  },
  {
    "title": "3Sum",
    "slug": "3sum-lc15-79",
    "canonicalKey": "lc15",
    "link": "https://leetcode.com/problems/3sum/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 9
  },
  {
    "title": "Container With Most Water",
    "slug": "container-with-most-water-lc11-79",
    "canonicalKey": "lc11",
    "link": "https://leetcode.com/problems/container-with-most-water/",
    "difficulty": "Medium",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striver79",
    "order": 10
  },
  {
    "title": "Trapping Rain Water",
    "slug": "trapping-rain-water-lc42-79",
    "canonicalKey": "lc42",
    "link": "https://leetcode.com/problems/trapping-rain-water/",
    "difficulty": "Hard",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striver79",
    "order": 11
  },
  {
    "title": "Valid Parentheses",
    "slug": "valid-parentheses-lc20-79",
    "canonicalKey": "lc20",
    "link": "https://leetcode.com/problems/valid-parentheses/",
    "difficulty": "Easy",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striver79",
    "order": 12
  },
  {
    "title": "Min Stack",
    "slug": "min-stack-lc155-79",
    "canonicalKey": "lc155",
    "link": "https://leetcode.com/problems/min-stack/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striver79",
    "order": 13
  },
  {
    "title": "Daily Temperatures",
    "slug": "daily-temperatures-lc739-79",
    "canonicalKey": "lc739",
    "link": "https://leetcode.com/problems/daily-temperatures/",
    "difficulty": "Medium",
    "category": "Stack",
    "pattern": "Stack",
    "sheet": "striver79",
    "order": 14
  },
  {
    "title": "Binary Search",
    "slug": "binary-search-lc704-79",
    "canonicalKey": "lc704",
    "link": "https://leetcode.com/problems/binary-search/",
    "difficulty": "Easy",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striver79",
    "order": 15
  },
  {
    "title": "Reverse Linked List",
    "slug": "reverse-linked-list-lc206-79",
    "canonicalKey": "lc206",
    "link": "https://leetcode.com/problems/reverse-linked-list/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 16
  },
  {
    "title": "Merge Two Sorted Lists",
    "slug": "merge-two-sorted-lists-lc21-79",
    "canonicalKey": "lc21",
    "link": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 17
  },
  {
    "title": "Linked List Cycle",
    "slug": "linked-list-cycle-lc141-79",
    "canonicalKey": "lc141",
    "link": "https://leetcode.com/problems/linked-list-cycle/",
    "difficulty": "Easy",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 18
  },
  {
    "title": "Remove Nth Node From End",
    "slug": "remove-nth-node-from-end-lc19-79",
    "canonicalKey": "lc19",
    "link": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 19
  },
  {
    "title": "Reorder List",
    "slug": "reorder-list-lc143-79",
    "canonicalKey": "lc143",
    "link": "https://leetcode.com/problems/reorder-list/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 20
  },
  {
    "title": "Add Two Numbers",
    "slug": "add-two-numbers-lc2-79",
    "canonicalKey": "lc2",
    "link": "https://leetcode.com/problems/add-two-numbers/",
    "difficulty": "Medium",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 21
  },
  {
    "title": "Merge K Sorted Lists",
    "slug": "merge-k-sorted-lists-lc23-79",
    "canonicalKey": "lc23",
    "link": "https://leetcode.com/problems/merge-k-sorted-lists/",
    "difficulty": "Hard",
    "category": "Linked List",
    "pattern": "Linked List",
    "sheet": "striver79",
    "order": 22
  },
  {
    "title": "Binary Tree Inorder Traversal",
    "slug": "binary-tree-inorder-traversal-lc94-79",
    "canonicalKey": "lc94",
    "link": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    "difficulty": "Unknown",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 23
  },
  {
    "title": "Maximum Depth of Binary Tree",
    "slug": "maximum-depth-of-binary-tree-lc104-79",
    "canonicalKey": "lc104",
    "link": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 24
  },
  {
    "title": "Diameter of Binary Tree",
    "slug": "diameter-of-binary-tree-lc543-79",
    "canonicalKey": "lc543",
    "link": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 25
  },
  {
    "title": "Balanced Binary Tree",
    "slug": "balanced-binary-tree-lc110-79",
    "canonicalKey": "lc110",
    "link": "https://leetcode.com/problems/balanced-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 26
  },
  {
    "title": "Invert Binary Tree",
    "slug": "invert-binary-tree-lc226-79",
    "canonicalKey": "lc226",
    "link": "https://leetcode.com/problems/invert-binary-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 27
  },
  {
    "title": "Same Tree",
    "slug": "same-tree-lc100-79",
    "canonicalKey": "lc100",
    "link": "https://leetcode.com/problems/same-tree/",
    "difficulty": "Easy",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 28
  },
  {
    "title": "Binary Tree Level Order Traversal",
    "slug": "binary-tree-level-order-traversal-lc102-79",
    "canonicalKey": "lc102",
    "link": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 29
  },
  {
    "title": "Lowest Common Ancestor of Binary Tree",
    "slug": "lowest-common-ancestor-of-binary-tree-lc236-79",
    "canonicalKey": "lc236",
    "link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    "difficulty": "Unknown",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 30
  },
  {
    "title": "Validate Binary Search Tree",
    "slug": "validate-binary-search-tree-lc98-79",
    "canonicalKey": "lc98",
    "link": "https://leetcode.com/problems/validate-binary-search-tree/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 31
  },
  {
    "title": "Kth Smallest Element in BST",
    "slug": "kth-smallest-element-in-bst-lc230-79",
    "canonicalKey": "lc230",
    "link": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 32
  },
  {
    "title": "Number of Islands",
    "slug": "number-of-islands-lc200-79",
    "canonicalKey": "lc200",
    "link": "https://leetcode.com/problems/number-of-islands/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 33
  },
  {
    "title": "Clone Graph",
    "slug": "clone-graph-lc133-79",
    "canonicalKey": "lc133",
    "link": "https://leetcode.com/problems/clone-graph/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 34
  },
  {
    "title": "Course Schedule",
    "slug": "course-schedule-lc207-79",
    "canonicalKey": "lc207",
    "link": "https://leetcode.com/problems/course-schedule/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 35
  },
  {
    "title": "Rotting Oranges",
    "slug": "rotting-oranges-lc994-79",
    "canonicalKey": "lc994",
    "link": "https://leetcode.com/problems/rotting-oranges/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 36
  },
  {
    "title": "Word Ladder",
    "slug": "word-ladder-lc127-79",
    "canonicalKey": "lc127",
    "link": "https://leetcode.com/problems/word-ladder/",
    "difficulty": "Hard",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 37
  },
  {
    "title": "Graph Valid Tree",
    "slug": "graph-valid-tree-lc261-79",
    "canonicalKey": "lc261",
    "link": "https://leetcode.com/problems/graph-valid-tree/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 38
  },
  {
    "title": "Number of Connected Components",
    "slug": "number-of-connected-components-lc323-79",
    "canonicalKey": "lc323",
    "link": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 39
  },
  {
    "title": "Climbing Stairs",
    "slug": "climbing-stairs-lc70-79",
    "canonicalKey": "lc70",
    "link": "https://leetcode.com/problems/climbing-stairs/",
    "difficulty": "Easy",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 40
  },
  {
    "title": "House Robber",
    "slug": "house-robber-lc198-79",
    "canonicalKey": "lc198",
    "link": "https://leetcode.com/problems/house-robber/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 41
  },
  {
    "title": "House Robber II",
    "slug": "house-robber-ii-lc213-79",
    "canonicalKey": "lc213",
    "link": "https://leetcode.com/problems/house-robber-ii/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 42
  },
  {
    "title": "Coin Change",
    "slug": "coin-change-lc322-79",
    "canonicalKey": "lc322",
    "link": "https://leetcode.com/problems/coin-change/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 43
  },
  {
    "title": "Longest Increasing Subsequence",
    "slug": "longest-increasing-subsequence-lc300-79",
    "canonicalKey": "lc300",
    "link": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 44
  },
  {
    "title": "Longest Common Subsequence",
    "slug": "longest-common-subsequence-lc1143-79",
    "canonicalKey": "lc1143",
    "link": "https://leetcode.com/problems/longest-common-subsequence/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 45
  },
  {
    "title": "Word Break",
    "slug": "word-break-lc139-79",
    "canonicalKey": "lc139",
    "link": "https://leetcode.com/problems/word-break/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 46
  },
  {
    "title": "Combination Sum",
    "slug": "combination-sum-lc39-79",
    "canonicalKey": "lc39",
    "link": "https://leetcode.com/problems/combination-sum/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striver79",
    "order": 47
  },
  {
    "title": "Subsets",
    "slug": "subsets-lc78-79",
    "canonicalKey": "lc78",
    "link": "https://leetcode.com/problems/subsets/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striver79",
    "order": 48
  },
  {
    "title": "Permutations",
    "slug": "permutations-lc46-79",
    "canonicalKey": "lc46",
    "link": "https://leetcode.com/problems/permutations/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striver79",
    "order": 49
  },
  {
    "title": "N-Queens",
    "slug": "n-queens-lc51-79",
    "canonicalKey": "lc51",
    "link": "https://leetcode.com/problems/n-queens/",
    "difficulty": "Hard",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striver79",
    "order": 50
  },
  {
    "title": "Word Search",
    "slug": "word-search-lc79-79",
    "canonicalKey": "lc79",
    "link": "https://leetcode.com/problems/word-search/",
    "difficulty": "Medium",
    "category": "Backtracking",
    "pattern": "Backtracking",
    "sheet": "striver79",
    "order": 51
  },
  {
    "title": "Merge Intervals",
    "slug": "merge-intervals-lc56-79",
    "canonicalKey": "lc56",
    "link": "https://leetcode.com/problems/merge-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 52
  },
  {
    "title": "Insert Interval",
    "slug": "insert-interval-lc57-79",
    "canonicalKey": "lc57",
    "link": "https://leetcode.com/problems/insert-interval/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 53
  },
  {
    "title": "Non-overlapping Intervals",
    "slug": "non-overlapping-intervals-lc435-79",
    "canonicalKey": "lc435",
    "link": "https://leetcode.com/problems/non-overlapping-intervals/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 54
  },
  {
    "title": "Meeting Rooms",
    "slug": "meeting-rooms-lc252-79",
    "canonicalKey": "lc252",
    "link": "https://leetcode.com/problems/meeting-rooms/",
    "difficulty": "Easy",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 55
  },
  {
    "title": "Meeting Rooms II",
    "slug": "meeting-rooms-ii-lc253-79",
    "canonicalKey": "lc253",
    "link": "https://leetcode.com/problems/meeting-rooms-ii/",
    "difficulty": "Medium",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 56
  },
  {
    "title": "Rotate Image",
    "slug": "rotate-image-lc48-79",
    "canonicalKey": "lc48",
    "link": "https://leetcode.com/problems/rotate-image/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "striver79",
    "order": 57
  },
  {
    "title": "Spiral Matrix",
    "slug": "spiral-matrix-lc54-79",
    "canonicalKey": "lc54",
    "link": "https://leetcode.com/problems/spiral-matrix/",
    "difficulty": "Medium",
    "category": "Math & Geometry",
    "pattern": "Math & Geometry",
    "sheet": "striver79",
    "order": 58
  },
  {
    "title": "Set Matrix Zeroes",
    "slug": "set-matrix-zeroes-lc73-79",
    "canonicalKey": "lc73",
    "link": "https://leetcode.com/problems/set-matrix-zeroes/",
    "difficulty": "Medium",
    "category": "Math / Miscellaneous",
    "pattern": "Math / Miscellaneous",
    "sheet": "striver79",
    "order": 59
  },
  {
    "title": "Pascal's Triangle",
    "slug": "pascal-s-triangle-lc118-79",
    "canonicalKey": "lc118",
    "link": "https://leetcode.com/problems/pascals-triangle/",
    "difficulty": "Unknown",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 60
  },
  {
    "title": "Majority Element",
    "slug": "majority-element-lc169-79",
    "canonicalKey": "lc169",
    "link": "https://leetcode.com/problems/majority-element/",
    "difficulty": "Unknown",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 61
  },
  {
    "title": "Missing Number",
    "slug": "missing-number-lc268-79",
    "canonicalKey": "lc268",
    "link": "https://leetcode.com/problems/missing-number/",
    "difficulty": "Easy",
    "category": "Bit Manipulation",
    "pattern": "Bit Manipulation",
    "sheet": "striver79",
    "order": 62
  },
  {
    "title": "Longest Consecutive Sequence",
    "slug": "longest-consecutive-sequence-lc128-79",
    "canonicalKey": "lc128",
    "link": "https://leetcode.com/problems/longest-consecutive-sequence/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 63
  },
  {
    "title": "Group Anagrams",
    "slug": "group-anagrams-lc49-79",
    "canonicalKey": "lc49",
    "link": "https://leetcode.com/problems/group-anagrams/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striver79",
    "order": 64
  },
  {
    "title": "Valid Anagram",
    "slug": "valid-anagram-lc242-79",
    "canonicalKey": "lc242",
    "link": "https://leetcode.com/problems/valid-anagram/",
    "difficulty": "Easy",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striver79",
    "order": 65
  },
  {
    "title": "Top K Frequent Elements",
    "slug": "top-k-frequent-elements-lc347-79",
    "canonicalKey": "lc347",
    "link": "https://leetcode.com/problems/top-k-frequent-elements/",
    "difficulty": "Medium",
    "category": "Heap / Priority Queue",
    "pattern": "Heap / Priority Queue",
    "sheet": "striver79",
    "order": 66
  },
  {
    "title": "Encode and Decode Strings",
    "slug": "encode-and-decode-strings-lc271-79",
    "canonicalKey": "lc271",
    "link": "https://leetcode.com/problems/encode-and-decode-strings/",
    "difficulty": "Medium",
    "category": "Arrays & Hashing",
    "pattern": "Arrays & Hashing",
    "sheet": "striver79",
    "order": 67
  },
  {
    "title": "Valid Palindrome",
    "slug": "valid-palindrome-lc125-79",
    "canonicalKey": "lc125",
    "link": "https://leetcode.com/problems/valid-palindrome/",
    "difficulty": "Easy",
    "category": "Two Pointers",
    "pattern": "Two Pointers",
    "sheet": "striver79",
    "order": 68
  },
  {
    "title": "Longest Substring Without Repeating Characters",
    "slug": "longest-substring-without-repeating-characters-lc3-79",
    "canonicalKey": "lc3",
    "link": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striver79",
    "order": 69
  },
  {
    "title": "Longest Repeating Character Replacement",
    "slug": "longest-repeating-character-replacement-lc424-79",
    "canonicalKey": "lc424",
    "link": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "difficulty": "Medium",
    "category": "Strings / Sliding Window",
    "pattern": "Strings / Sliding Window",
    "sheet": "striver79",
    "order": 70
  },
  {
    "title": "Minimum Window Substring",
    "slug": "minimum-window-substring-lc76-79",
    "canonicalKey": "lc76",
    "link": "https://leetcode.com/problems/minimum-window-substring/",
    "difficulty": "Hard",
    "category": "Intervals",
    "pattern": "Intervals",
    "sheet": "striver79",
    "order": 71
  },
  {
    "title": "Sliding Window Maximum",
    "slug": "sliding-window-maximum-lc239-79",
    "canonicalKey": "lc239",
    "link": "https://leetcode.com/problems/sliding-window-maximum/",
    "difficulty": "Hard",
    "category": "Sliding Window",
    "pattern": "Sliding Window",
    "sheet": "striver79",
    "order": 72
  },
  {
    "title": "Koko Eating Bananas",
    "slug": "koko-eating-bananas-lc875-79",
    "canonicalKey": "lc875",
    "link": "https://leetcode.com/problems/koko-eating-bananas/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striver79",
    "order": 73
  },
  {
    "title": "Search a 2D Matrix",
    "slug": "search-a-2d-matrix-lc74-79",
    "canonicalKey": "lc74",
    "link": "https://leetcode.com/problems/search-a-2d-matrix/",
    "difficulty": "Medium",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striver79",
    "order": 74
  },
  {
    "title": "Median of Two Sorted Arrays",
    "slug": "median-of-two-sorted-arrays-lc4-79",
    "canonicalKey": "lc4",
    "link": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "difficulty": "Hard",
    "category": "Binary Search",
    "pattern": "Binary Search",
    "sheet": "striver79",
    "order": 75
  },
  {
    "title": "Serialize and Deserialize Binary Tree",
    "slug": "serialize-and-deserialize-binary-tree-lc297-79",
    "canonicalKey": "lc297",
    "link": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 76
  },
  {
    "title": "Binary Tree Maximum Path Sum",
    "slug": "binary-tree-maximum-path-sum-lc124-79",
    "canonicalKey": "lc124",
    "link": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "difficulty": "Hard",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 77
  },
  {
    "title": "Construct Binary Tree from Preorder and Inorder",
    "slug": "construct-binary-tree-from-preorder-and-inorder-lc105-79",
    "canonicalKey": "lc105",
    "link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    "difficulty": "Medium",
    "category": "Trees",
    "pattern": "Trees",
    "sheet": "striver79",
    "order": 78
  },
  {
    "title": "Course Schedule II",
    "slug": "course-schedule-ii-lc210-79",
    "canonicalKey": "lc210",
    "link": "https://leetcode.com/problems/course-schedule-ii/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 79
  },
  {
    "title": "Pacific Atlantic Water Flow",
    "slug": "pacific-atlantic-water-flow-lc417-79",
    "canonicalKey": "lc417",
    "link": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    "difficulty": "Medium",
    "category": "Graphs",
    "pattern": "Graphs",
    "sheet": "striver79",
    "order": 80
  },
  {
    "title": "Partition Equal Subset Sum",
    "slug": "partition-equal-subset-sum-lc416-79",
    "canonicalKey": "lc416",
    "link": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "difficulty": "Medium",
    "category": "1-D Dynamic Programming",
    "pattern": "1-D Dynamic Programming",
    "sheet": "striver79",
    "order": 81
  },
  {
    "title": "Unique Paths",
    "slug": "unique-paths-lc62-79",
    "canonicalKey": "lc62",
    "link": "https://leetcode.com/problems/unique-paths/",
    "difficulty": "Medium",
    "category": "Dynamic Programming",
    "pattern": "Dynamic Programming",
    "sheet": "striver79",
    "order": 82
  },
  {
    "title": "Minimum Path Sum",
    "slug": "minimum-path-sum-lc64-79",
    "canonicalKey": "lc64",
    "link": "https://leetcode.com/problems/minimum-path-sum/",
    "difficulty": "Medium",
    "category": "Dynamic Programming & Backtracking",
    "pattern": "Dynamic Programming & Backtracking",
    "sheet": "striver79",
    "order": 83
  },
  {
    "title": "Edit Distance",
    "slug": "edit-distance-lc72-79",
    "canonicalKey": "lc72",
    "link": "https://leetcode.com/problems/edit-distance/",
    "difficulty": "Medium",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "striver79",
    "order": 84
  },
  {
    "title": "Regular Expression Matching",
    "slug": "regular-expression-matching-lc10-79",
    "canonicalKey": "lc10",
    "link": "https://leetcode.com/problems/regular-expression-matching/",
    "difficulty": "Hard",
    "category": "2-D Dynamic Programming",
    "pattern": "2-D Dynamic Programming",
    "sheet": "striver79",
    "order": 85
  }
];
